---
title: "Covariance functions on an interval of $\\mathbb{R}$"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendeblack HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(2) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = FALSE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(MetricGraph)
library(ggplot2)
library(reshape2)
library(dplyr)
library(viridis)
library(plotly)
library(patchwork)
library(slackr)
source("keys.R")
slackr_setup(token = token) # token comes from keys.R
```

```{r}
reticulate::use_python(
  "/home/rierasl/miniconda3/envs/phdenv/bin/python",
  required = TRUE
)

reticulate::py_config()
```


```{r}
capture.output(
  knitr::purl(here::here("all_functions.Rmd"), output = here::here("all_functions.R")),
  file = here::here("old/purl_log.txt")
)
capture.output(
  knitr::purl(here::here("matern_functions.Rmd"), output = here::here("matern_functions.R")),
  file = here::here("old/purl_log.txt")
)

source(here::here("all_functions.R"))
source(here::here("matern_functions.R"))
```


```{r}
# Function to build an interval graph and create a mesh
gets_graph_interval <- function(h, ell){
  edge <- rbind(c(0,0),c(ell,0))
  edges = list(edge)
  graph <- metric_graph$new(edges = edges)
  graph$build_mesh(h = h)
  return(graph)
}
```



```{r}
# Parameters of the approximation
h = 0.02
ell = 2

# Get the graph and build the mesh
graph = gets_graph_interval(h = h, ell = ell)
graph$compute_fem()

nodes <- graph$mesh$V[,1]
randd <- rnorm(length(nodes))

type = "covariance"
type_rational_approximation = "chebfun"
rho = 0.5
m = 1
nu = 1.5
sigma = 1

kappa = sqrt(8*nu)/rho
tau = sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  #sigma = 1, d = 1
alpha = nu + 1/2
```

```{r}
dist_mat <- abs(outer(nodes, nodes, "-"))
Sigma_Matern <- matern.covariance(h = dist_mat, kappa = kappa, nu = nu, sigma = sigma)
```




```{r}
# Get the approximate covariance matrix
op <- matern.operators(alpha = alpha, 
                      kappa = kappa, 
                      tau = tau,
                      m = m, 
                      graph = graph,
                      type = type,
                      type_rational_approximation = type_rational_approximation)

Sigma_FEM <- covariance_mesh(op)
```



```{r}
Sigma_r <- Sigma_FEM*NA
for (i in 1:length(nodes)) {
  for (j in 1:length(nodes)) {
    Sigma_r[i,j] = sigma^2*matern.p.joint(s = nodes[i], t = nodes[j], kappa = kappa, p = 0, alpha = alpha)[1,1]
  }
}
```


```{r}
r_bridge <- function(t1, t2, kappa, alpha, sigma, ell){
  nu <- alpha - 1/2
  r1_t1_0 <- sigma^2*matern.p.joint(s = t1, t = 0, kappa = kappa, p = 0, alpha = alpha)[1,]
  r1_t1_ell <- sigma^2*matern.p.joint(s = t1, t = ell, kappa = kappa, p = 0, alpha = alpha)[1,]
  
  r_0_0 <- sigma^2*matern.p.joint(s = 0, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r_0_ell <- sigma^2*matern.p.joint(s = 0, t = ell, kappa = kappa, p = 0, alpha = alpha)
  r_ell_0 <- sigma^2*matern.p.joint(s = ell, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r_ell_ell <- sigma^2*matern.p.joint(s = ell, t = ell, kappa = kappa, p = 0, alpha = alpha)
  
  r1_0_t2 <- sigma^2*matern.p.joint(s = 0, t = t2, kappa = kappa, p = 0, alpha = alpha)[1,]
  r1_ell_t2 <- sigma^2*matern.p.joint(s = ell, t = t2, kappa = kappa, p = 0, alpha = alpha)[1,]
  
  r1_h <- matrix(c(r1_t1_0, r1_t1_ell), nrow = 1, ncol = 2*alpha)
  r1_v <- matrix(c(r1_0_t2, r1_ell_t2), nrow = 2*alpha, ncol = 1)
  
  cov <- matern.covariance(h = t1 - t2, kappa = kappa, nu = nu, sigma = sigma) - r1_h %*% solve(rbind(cbind(r_0_0, r_0_ell), cbind(r_ell_0, r_ell_ell)), r1_v)
  return(as.numeric(cov))
}
```


```{r}
r_hat <- function(t1, t2, kappa, alpha, sigma, ell){
  nu <- alpha - 1/2
  r1_t1_0 <- sigma^2*matern.p.joint(s = t1, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r1_t1_ell <- sigma^2*matern.p.joint(s = t1, t = ell, kappa = kappa, p = 0, alpha = alpha)
  
  r_0_0 <- sigma^2*matern.p.joint(s = 0, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r_0_ell <- -sigma^2*matern.p.joint(s = 0, t = ell, kappa = kappa, p = 0, alpha = alpha)
  r_ell_0 <- -sigma^2*matern.p.joint(s = ell, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r_ell_ell <- sigma^2*matern.p.joint(s = 0, t = 0, kappa = kappa, p = 0, alpha = alpha)
  
  r1_0_t2 <- sigma^2*matern.p.joint(s = t2, t = 0, kappa = kappa, p = 0, alpha = alpha)
  r1_ell_t2 <- sigma^2*matern.p.joint(s = t2, t = ell, kappa = kappa, p = 0, alpha = alpha)
  
  
  cov <- sigma^2*matern.p.joint(s = t1, t = t2, kappa = kappa, p = 0, alpha = alpha) + cbind(r1_t1_0, r1_t1_ell) %*% solve(rbind(cbind(r_0_0, r_0_ell), cbind(r_ell_0, r_ell_ell)), rbind(r1_0_t2, r1_ell_t2))
  return(as.numeric(cov[1,1]))
}
```



```{r}
Sigma_bridge <- Sigma_FEM*NA
for (i in 1:length(nodes)) {
  for (j in 1:length(nodes)) {
    Sigma_bridge[i,j] = r_bridge(t1 = nodes[i], t2 = nodes[j], kappa = kappa, alpha = alpha, sigma = sigma, ell = ell)
  }
}


```



```{r}
Sigma_hat <- Sigma_FEM*NA
for (i in 1:length(nodes)) {
  for (j in 1:length(nodes)) {
    Sigma_hat[i,j] = r_hat(t1 = nodes[i], t2 = nodes[j], kappa = kappa, alpha = alpha, sigma = sigma, ell = ell)
  }
}
```

```{r}
# Compute errors
L_2_error_Matern_FEM <- sqrt(as.double(t(graph$mesh$weights) %*% (Sigma_Matern - Sigma_FEM)^2 %*% graph$mesh$weights))
L_2_error_Matern_r <- sqrt(as.double(t(graph$mesh$weights) %*% (Sigma_Matern - Sigma_r)^2 %*% graph$mesh$weights))
L_2_error_Matern_bridge <- sqrt(as.double(t(graph$mesh$weights) %*% (Sigma_Matern - Sigma_bridge)^2 %*% graph$mesh$weights))
L_2_error_Matern_hat <- sqrt(as.double(t(graph$mesh$weights) %*% (Sigma_Matern - Sigma_hat)^2 %*% graph$mesh$weights))

L_2_error_FEM_hat <- sqrt(as.double(t(graph$mesh$weights) %*% (Sigma_FEM - Sigma_hat)^2 %*% graph$mesh$weights))

# Print messages
cat(" L2 error (Matern - FEM):", L_2_error_Matern_FEM, "\n",
    "L2 error (Matern - r):", L_2_error_Matern_r, "\n",
    "L2 error (Matern - bridge):", L_2_error_Matern_bridge, "\n",
    "L2 error (Matern - hat):", L_2_error_Matern_hat, "\n",
    "L2 error (FEM - hat):", L_2_error_FEM_hat, "\n")
```



```{r}
point  <- c(1,0.85)
loc <- graph$coordinates(PtE = point)
m1 <- which.min((graph$mesh$V[,1]-loc[1])^2 + (graph$mesh$V[,2]-loc[2])^2)
```


```{r}
right_order <- c(1, 3:length(nodes), 2)
nodes_order <- nodes[right_order]

dfPoint <- data.frame(x = nodes_order[m1], y = 0, z = 0)
```



```{r}
one_row_Sigma_Matern <- Sigma_Matern[right_order,right_order][m1,]
one_row_Sigma_FEM <- Sigma_FEM[right_order,right_order][m1,]
one_row_Sigma_bridge <- Sigma_bridge[right_order,right_order][m1,]
one_row_Sigma_hat <- Sigma_hat[right_order,right_order][m1,]
df <- data.frame(x = nodes_order, y = 0,
                 Matern = one_row_Sigma_Matern, 
                 FEM = one_row_Sigma_FEM,
                 bridge = one_row_Sigma_bridge,
                 hat = one_row_Sigma_hat) %>%
  mutate(max = pmax(Matern, FEM, bridge, hat))

df_vertex <- data.frame(x = nodes[1:2], y = 0, z = 0)
x_range <- range(df$x, na.rm = TRUE)*1.001
y_range <- range(df$y, na.rm = TRUE)*1.001
z_range <- range(df$max, na.rm = TRUE)*1.001
```


```{r}
rv <- 2
myeye <- list(x = 1*rv, y = -2*rv, z = 1*rv)
mycenter <- list(x = 0, y = 0, z = 0)

viewer_change <- 1  # >1 further, <1 closer

neweye <- list(
  x = mycenter$x + (myeye$x - mycenter$x) * viewer_change,
  y = mycenter$y + (myeye$y - mycenter$y) * viewer_change,
  z = mycenter$z + (myeye$z - mycenter$z) * viewer_change
)
```


```{r}
p_cov <- plot_ly() %>%
  add_trace(data = df, 
            x = ~x, y = ~y, z = ~Matern*0, 
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "black", width = 7), 
            name = "graph", showlegend = FALSE) %>%
  add_trace(data = df_vertex, 
            x = ~x, y = ~y, z = ~z, 
            type = "scatter3d", 
            mode = "markers", 
            marker = list(color = "black", size = 7), 
            name = "vertex", showlegend = FALSE) %>%
  add_trace(data = dfPoint, 
            x = ~x, y = ~y, z = ~z, 
            type = "scatter3d", 
            mode = "markers", 
            marker = list(color = "darkviolet", size = 7), 
            name = "point", showlegend = FALSE) %>%
  add_trace(x = rep(df$x, each = 3), 
            y = rep(df$y, each = 3),
            z = unlist(lapply(df$max, function(zj) c(0, zj, NA))),
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "gray", width = 0.5),
            name = "support", 
            showlegend = FALSE) %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~Matern, type = "scatter3d", mode = "lines", line = list(color = "blue", width = 7), name = "Matérn") %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~FEM, type = "scatter3d", mode = "lines", line = list(color = "red", width = 7), name = "FEM") %>%
  add_trace(data = df, x = ~x, y = ~y, z =~bridge, type = "scatter3d", mode = "lines", line = list(color = "green", width = 7), name = "bridge") %>%
  add_trace(data = df, x = ~x, y = ~y, z= ~hat, type = "scatter3d", mode = "lines", line = list(color = "black", width = 7), name = "boundaryless") %>%
  config(mathjax = 'cdn') %>%
  layout(font = list(family = "Palatino Linotype"), # Palatino Linotype
    margin = list(l = 0, r = 0, b = 0, t = 0),
    legend = list(
    x = 0,
    y = 0.8, # default = 1
    xanchor = "left",
    yanchor = "top",
    font = list(size = 26)#, orientation = "h", itemwidth = 80
  ),
    scene = list(
    xaxis = list(title = list(text = latex2exp::TeX("x"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18),  range = x_range),
              yaxis = list(title = list(text = latex2exp::TeX("y"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18), range = y_range),
              zaxis = list(title = list(text = latex2exp::TeX("z"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18)),
    aspectratio = list(x = ell, y = 1, z = 1),
                      camera = list(eye = neweye,
                                    center = mycenter)))
save(p_cov, file = here::here("data_files/p_cov.RData"))
```




```{r}
one_row_Sigma_Matern <- diag(Sigma_Matern)[right_order]
one_row_Sigma_FEM <- diag(Sigma_FEM)[right_order]
one_row_Sigma_bridge <- diag(Sigma_bridge)[right_order]
one_row_Sigma_hat <- diag(Sigma_hat)[right_order]
df <- data.frame(x = nodes_order, y = 0,
                 Matern = one_row_Sigma_Matern, 
                 FEM = one_row_Sigma_FEM,
                 bridge = one_row_Sigma_bridge,
                 hat = one_row_Sigma_hat) %>%
  mutate(max = pmax(Matern, FEM, bridge, hat))

df_vertex <- data.frame(x = nodes[1:2], y = 0, z = 0)

x_range <- range(df$x, na.rm = TRUE)*1.001
y_range <- range(df$y, na.rm = TRUE)*1.001
z_range <- range(df$max, na.rm = TRUE)*1.001
```


```{r}
rv <- 2
```


```{r}
p_diag <- plot_ly() %>%
  add_trace(data = df, 
            x = ~x, y = ~y, z = ~Matern*0, 
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "black", width = 7), 
            name = "graph", showlegend = FALSE) %>%
  add_trace(data = df_vertex, 
            x = ~x, y = ~y, z = ~z, 
            type = "scatter3d", 
            mode = "markers", 
            marker = list(color = "black", size = 7), 
            name = "vertex", showlegend = FALSE) %>%
  add_trace(x = rep(df$x, each = 3), 
            y = rep(df$y, each = 3),
            z = unlist(lapply(df$max, function(zj) c(0, zj, NA))),
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "gray", width = 0.5),
            name = "support", 
            showlegend = FALSE) %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~Matern, type = "scatter3d", mode = "lines", line = list(color = "blue", width = 7), name = "Matérn", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~FEM, type = "scatter3d", mode = "lines", line = list(color = "red", width = 7), name = "FEM", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z =~bridge, type = "scatter3d", mode = "lines", line = list(color = "green", width = 7), name = "bridge", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z= ~hat, type = "scatter3d", mode = "lines", line = list(color = "black", width = 7), name = "boundaryless", showlegend = TRUE) %>%
  config(mathjax = 'cdn') %>%
  layout(font = list(family = "Palatino Linotype"), # Palatino Linotype
    margin = list(l = 0, r = 0, b = 0, t = 0),
    legend = list(
    x = 0,
    y = 0.8, # default = 1
    xanchor = "left",
    yanchor = "top",
    font = list(size = 26)#, orientation = "h", itemwidth = 80
  ),
    scene = list(
    xaxis = list(title = list(text = latex2exp::TeX("x"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18),  range = x_range),
              yaxis = list(title = list(text = latex2exp::TeX("y"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18), range = y_range),
              zaxis = list(title = list(text = latex2exp::TeX("z"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18)),
    aspectratio = list(x = ell, y = 1, z = 1),
                      camera = list(eye = list(x = 1*rv, y = -2*rv, z =1*rv),
                                    center = list(x = 0, y = 0, z = 0))))
save(p_diag, file = here::here("data_files/p_diag.RData"))
```



```{r}
eps <- 1e-16
Sigma_bridge <- Sigma_bridge + diag(eps, nrow(Sigma_bridge))
Sigma_hat <- Sigma_hat + diag(eps, nrow(Sigma_hat))
R = chol(Sigma_FEM)
x_FEM = t(R) %*% randd
R = chol(Sigma_Matern)
x_Matern = t(R) %*% randd
R = chol(Sigma_bridge)
x_bridge = t(R) %*% randd
R = chol(Sigma_hat)
x_hat = t(R) %*% randd
```


```{r}
# Compute errors
L_2_error_Matern_FEM_sample <- sqrt(as.double(t(graph$mesh$weights) %*% (x_Matern - x_FEM)^2))
L_2_error_Matern_bridge_sample <- sqrt(as.double(t(graph$mesh$weights) %*% (x_Matern - x_bridge)^2))
L_2_error_Matern_hat_sample <- sqrt(as.double(t(graph$mesh$weights) %*% (x_Matern - x_hat)^2 ))
L_2_error_FEM_hat_sample <- sqrt(as.double(t(graph$mesh$weights) %*% (x_FEM - x_hat)^2))

# Print messages
cat(" L2 error (Matern - FEM) sample:", L_2_error_Matern_FEM_sample, "\n",
    "L2 error (Matern - bridge) sample:", L_2_error_Matern_bridge_sample, "\n",
    "L2 error (Matern - hat) sample:", L_2_error_Matern_hat_sample, "\n",
    "L2 error (FEM - hat) sample:", L_2_error_FEM_hat_sample, "\n")
```





```{r}
one_row_Sigma_Matern <- x_Matern[right_order]
one_row_Sigma_FEM <- x_FEM[right_order]
one_row_Sigma_bridge <- x_bridge[right_order]
one_row_Sigma_hat <- x_hat[right_order]
df <- data.frame(x = nodes_order, y = 0,
                 Matern = one_row_Sigma_Matern, 
                 FEM = one_row_Sigma_FEM,
                 bridge = one_row_Sigma_bridge,
                 hat = one_row_Sigma_hat) %>%
  mutate(max = pmax(Matern, FEM, bridge, hat))

df_vertex <- data.frame(x = nodes[1:2], y = 0, z = 0)

x_range <- range(df$x, na.rm = TRUE)*1.001
y_range <- range(df$y, na.rm = TRUE)*1.001
z_range <- range(df$max, na.rm = TRUE)*1.001
```


```{r}
rv <- 2
```



```{r}
p_sample <- plot_ly() %>%
  add_trace(data = df, 
            x = ~x, y = ~y, z = ~Matern*0, 
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "black", width = 7), 
            name = "graph", showlegend = FALSE) %>%
  add_trace(data = df_vertex, 
            x = ~x, y = ~y, z = ~z, 
            type = "scatter3d", 
            mode = "markers", 
            marker = list(color = "black", size = 7), 
            name = "vertex", showlegend = FALSE) %>%
  add_trace(x = rep(df$x, each = 3), 
            y = rep(df$y, each = 3),
            z = unlist(lapply(df$max, function(zj) c(0, zj, NA))),
            type = "scatter3d", 
            mode = "lines", 
            line = list(color = "gray", width = 0.5),
            name = "support", 
            showlegend = FALSE) %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~Matern, type = "scatter3d", mode = "lines", line = list(color = "blue", width = 7), name = "Matérn", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z = ~FEM, type = "scatter3d", mode = "lines", line = list(color = "red", width = 7), name = "FEM", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z =~bridge, type = "scatter3d", mode = "lines", line = list(color = "green", width = 7), name = "bridge", showlegend = TRUE) %>%
  add_trace(data = df, x = ~x, y = ~y, z= ~hat, type = "scatter3d", mode = "lines", line = list(color = "black", width = 7), name = "boundaryless", showlegend = TRUE) %>%
  config(mathjax = 'cdn') %>%
  layout(font = list(family = "Palatino Linotype"), # Palatino Linotype
    margin = list(l = 0, r = 0, b = 0, t = 0),
    legend = list(
    x = 0,
    y = 0.8, # default = 1
    xanchor = "left",
    yanchor = "top",
    font = list(size = 26)#, orientation = "h", itemwidth = 80
  ),
    scene = list(
    xaxis = list(title = list(text = latex2exp::TeX("x"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18),  range = x_range),
              yaxis = list(title = list(text = latex2exp::TeX("y"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18), range = y_range),
              zaxis = list(title = list(text = latex2exp::TeX("z"), font = list(color = "black", size = 26)),  
                           tickfont = list(color = "black", size = 18)),
    aspectratio = list(x = ell, y = 1, z = 1),
                      camera = list(eye = list(x = 1*rv, y = -2*rv, z =1*rv),
                                    center = list(x = 0, y = 0, z = 0))))
save(p_sample, file = here::here("data_files/p_sample.RData"))
```


```{r}
save_plotly_figure_fixed(p_cov, dpi = 300, scale = 2, viewer_change = 0.65)
save_plotly_figure_fixed(p_diag, dpi = 300, scale = 2, viewer_change = 0.65)
save_plotly_figure_fixed(p_sample, dpi = 300, scale = 2, viewer_change = 0.65)

png_files <- c("/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_cov.png",
               "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_diag.png",
               "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_sample.png")
output_file <- "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_cov_diag_sample.png"

combine_pngs_with_gap(png_files, output_file, gap = 200)
```

```{r}
# png_files <- c("/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_cov.png", 
#                "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_diag.png",
#                "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_sample.png")
# output_file <- "/home/rierasl/Desktop/ratAPPROX/data_files/plotlypdf/p_cov_diag_sample.png"
# # cmd <- paste(
# #   "convert",
# #   paste(shQuote(png_files), collapse = " "),
# #   "+append",
# #   shQuote(output_file)
# # )
# # 
# # system(cmd, ignore.stdout = TRUE, ignore.stderr = TRUE)
# 
# gap <- 200  # pixels between images
# 
# # build sequence: img spacer img spacer img
# parts <- c()
# for (i in seq_along(png_files)) {
#   parts <- c(parts, shQuote(png_files[i]))
#   if (i < length(png_files)) {
#     parts <- c(parts, sprintf("\\( -size %dx1 xc:white \\)", gap))
#   }
# }
# 
# cmd <- paste(
#   "convert",
#   paste(parts, collapse = " "),
#   "+append",
#   shQuote(output_file)
# )
# 
# system(cmd, ignore.stdout = TRUE, ignore.stderr = TRUE)
```


:::: {style="display: grid; grid-template-columns: 580px 580px 580px; grid-column-gap: 0px;"}


::: {}


```{r, eval =TRUE, fig.height = 7, out.width="100%", fig.cap = captioner("Animation.")}
load(here::here("data_files/p_cov.RData"))
p_cov
```


:::

::: {}

```{r, eval =TRUE, fig.height = 7, out.width="100%", fig.cap = captioner("Still.")}
load(here::here("data_files/p_diag.RData"))
p_diag
```


:::

::: {}

```{r, eval =TRUE, fig.height = 7, out.width="100%", fig.cap = captioner("Still.")}
load(here::here("data_files/p_sample.RData"))
p_sample
```


:::



::::


```{r, eval = TRUE}
grateful::cite_packages(output = "paragraph", out.dir = ".")
```

