---
title: "d1"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendeblack HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(MetricGraph)
library(ggplot2)
library(reshape2)
library(dplyr)
library(viridis)
library(plotly)
library(patchwork)

library(Matrix)
```


```{r}
capture.output(
  knitr::purl(here::here("all_functions.Rmd"), output = here::here("all_functions.R")),
  file = here::here("old/purl_log.txt")
)
capture.output(
  knitr::purl(here::here("matern_functions.Rmd"), output = here::here("matern_functions.R")),
  file = here::here("old/purl_log.txt")
)

# load the functions
source(here::here("all_functions.R"))
source(here::here("matern_functions.R"))
```



```{r}
# parameters
h <- 0.2
kappa <- 5
sigma <- 0.8
alpha <- 1.4
m <- 4
nu <- alpha - 0.5
tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))
n.overkill <- 1000


FLIPPED <- TRUE


# build a graph with a mesh
graph_initial <- gets.graph.tadpole(flip_edge = FLIPPED)
graph <- graph_initial$clone()




graph_initial$build_mesh(h = h)
graph_initial$compute_fem()


# add mesh locations as observations
graph$add_observations(
  data = graph_initial$get_mesh_locations() %>% 
    as.data.frame() %>% 
    mutate(y = 1) %>% 
    rename(edge_number = V1, distance_on_edge = V2) %>% 
    mutate(dummy = 1:length(y)),
  edge_number = "edge_number",
  distance_on_edge = "distance_on_edge",
  data_coords = "PtE",
  normalized = TRUE, 
  clear_obs = TRUE)

# add observations as vertices
graph$observation_to_vertex()


Approx_Sigma <- gets_cov_mat_rat_approx_alpha_1_to_2(
  graph = graph, 
  kappa = kappa, 
  tau = tau, 
  alpha = alpha, 
  m = m)

```


```{r}
graph_initial$plot_function(X = Approx_Sigma[,2], type = "plotly", interpolate_plot = FALSE)
```


```{r}
graph_initial$add_observations(
  data = graph_initial$get_mesh_locations() %>% 
    as.data.frame() %>% 
    mutate(y = 1) %>% 
    rename(edge_number = V1, distance_on_edge = V2) %>% 
    mutate(cov = Approx_Sigma[,2]),
  edge_number = "edge_number",
  distance_on_edge = "distance_on_edge",
  data_coords = "PtE",
  normalized = TRUE, 
  clear_obs = TRUE)

graph_initial$observation_to_vertex()
```


```{r}
graph_initial$plot_function(data = "cov", type = "plotly", interpolate_plot = FALSE)
```


