---
title: "Numerical error"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


Go back to the [About page](about.html).

Let us set some global options for all code chunks in this document.


```{r}
# Create a clipboard button on the rendered HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(593) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}
# Define the function to truncate a number to two decimal places
truncate_to_two <- function(x) {
  truncated <- floor(x * 100) / 100
  sprintf("%.2f", truncated)
}
```

# Import libraries

```{r, eval = TRUE}
library(MetricGraph)
library(Matrix)
library(rSPDE)

library(dplyr)
library(tidyverse)
library(plotly)
library(ggplot2)
library(latex2exp)
library(ggtext)

library(grateful) # Cite all loaded packages
library(here) # here::here() starts from the home directory

library(slackr)
source("keys.R")
slackr_setup(token = token) # token comes from keys.R
```



```{r}
# get the functions from the Rmd files
knitr::purl(here::here("all_functions.Rmd"), output = here::here("all_functions.R"))
knitr::purl(here::here("matern_functions.Rmd"), output = here::here("matern_functions.R"))

# load the functions
source(here::here("all_functions.R"))
source(here::here("matern_functions.R"))

```

```{r}
alphaVector <- c(seq(0.51,0.59,by=0.01),
           seq(0.6,0.9,by=0.05), 
           seq(0.91,1.09,by=0.01),
           seq(1.1,1.9,by=0.05), 
           seq(1.91,2.09,by=0.01),
           seq(2.1,2.9,by=0.05), 
           seq(2.91,3,by=0.01)) 
mVector <- c(1,2,3,4,5)
rhoVector <- c(0.1, 0.5, 1, 2)/10

sigma <- 1
h <- 0.01
nOverkill <- 1000
type_rational_approx <- "chebfun"
type_interp <- "spline"


dat <- expand_grid(
  alpha = alphaVector,
  m = mVector,
  rho = rhoVector
) |> 
  mutate(L2ErrorRational = 0, 
         LinfErrorRational = 0, 
         timeElapsedRational = 0, 
         L2ErrorFEM = 0,
         LinfErrorFEM = 0,
         timeElapsedFEM = 0,
         timeElapsedTrue = 0)


graphFEM <- gets.graph.tadpole(flip_edge = FALSE)
graph <- graphFEM$clone()

graphFEM$build_mesh(h = h)

mesh_locations <- graphFEM$get_mesh_locations() %>% 
  as.data.frame() %>% 
  mutate(dummy = 1) %>%
  rename(edge_number = V1, distance_on_edge = V2)

# add mesh locations as observations
graph$add_observations(
  data = mesh_locations,
  normalized = TRUE)

graph$observation_to_vertex()
```


```
{r}
unique_params <- unique(dat[, c("alpha", "rho")])
trueSigma_list <- list()
timeTrue_list <- list()
for (j in 1:nrow(unique_params)) {
  alpha_j <- unique_params$alpha[j]
  rho_j <- unique_params$rho[j]
  
  nu_j <- alpha_j - 1/2
  kappa_j <- sqrt(8 * nu_j) / rho_j
  tau_j <- sqrt(gamma(nu_j) / (sigma^2 * kappa_j^(2*nu_j) * (4*pi)^(1/2) * gamma(nu_j + 1/2)))
  
  key <- sprintf("%.6f_%.6f", alpha_j, rho_j)
  
  tryCatch({
  timeTrue_list[[key]] <- system.time({
    trueSigma_list[[key]] <- gets_true_cov_mat(
      graph = graphFEM,
      kappa = kappa_j,
      tau = tau_j,
      alpha = alpha_j,
      n.overkill = nOverkill
    )
  })["elapsed"]
  }, error = function(err){
    warning(paste0("Error occurred while computing true covariance for alpha = ", alpha_j, 
                   " and rho = ", rho_j, 
                   ": ", conditionMessage(err)))
    slackr_msg(text = paste0("Error occurred while computing true covariance for alpha = ", alpha_j, 
                   " and rho = ", rho_j, 
                   ": ", conditionMessage(err)),
               channel = "#research")
    trueSigma_list[[key]] <- NA
    timeTrue_list[[key]] <- NA
  })
}

save(trueSigma_list, timeTrue_list, file = "~/Desktop/trueSigma_list.RData")
```


```
{r}
load("~/Desktop/trueSigma_list.RData")
for (i in 1:nrow(dat)) {
  dat_i <- dat[i, ]
  alpha <- dat_i$alpha
  m <- dat_i$m
  rho <- dat_i$rho
  
  nu <- alpha - 1/2
  kappa <- sqrt(8*nu)/rho
  tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  
  
  tryCatch({
            key <- sprintf("%.6f_%.6f", alpha, rho)

            trueSigma <- trueSigma_list[[key]]
            timeElapsedTrue <- timeTrue_list[[key]]
            
            timeElapsedFEM <- system.time({
            FEMSigma <- covariance_mesh(
              matern.operators(
                alpha = alpha, 
                kappa = kappa, 
                tau = tau,
                m = m, 
                graph = graphFEM,
                type = "covariance",
                type_rational_approximation = type_rational_approx))
            })["elapsed"]
            
            timeElapsedRational <- system.time({
            ratSigma <- rat_covariance(
              graph = graph, 
              kappa = kappa, 
              tau = tau, 
              alpha = alpha, 
              m = m,
              type_rational_approx = type_rational_approx,
              type_interp = type_interp,
              build_cov = TRUE)
            })["elapsed"]
            
            # computing the errors
            dat[i, ]$LinfErrorRational <- max(abs(trueSigma - ratSigma))
            dat[i, ]$L2ErrorRational <- sqrt(as.double(t(graphFEM$mesh$weights)%*%(trueSigma - ratSigma)^2%*%graphFEM$mesh$weights))
            
            dat[i, ]$LinfErrorFEM <- max(abs(trueSigma - FEMSigma))
            dat[i, ]$L2ErrorFEM <- sqrt(as.double(t(graphFEM$mesh$weights)%*%(trueSigma - FEMSigma)^2%*%graphFEM$mesh$weights))
            
            dat[i, ]$timeElapsedRational <- timeElapsedRational
            dat[i, ]$timeElapsedFEM <- timeElapsedFEM
            dat[i, ]$timeElapsedTrue <- timeElapsedTrue
            
            }, error = function(err){
              warning(paste0("Error occurred at iteration rho = ", rho, 
                            ", kappa = ", kappa,
                            ", m = ", m, 
                            ", alpha = ", alpha,
                            ", nu = ", nu, 
                            ", Error:", conditionMessage(err)))
              slackr_msg(text = paste0("Error occurred at iteration rho = ", rho, 
                          ", kappa = ", kappa,
                          ", m = ", m, 
                          ", alpha = ", alpha,
                          ", nu = ", nu, 
                          ", Error:", conditionMessage(err)),
                         channel = "#research")
              dat[i, ]$LinfErrorRational <- NA
              dat[i, ]$L2ErrorRational <- NA
            
              dat[i, ]$LinfErrorFEM <- NA
              dat[i, ]$L2ErrorFEM <- NA
              
              dat[i, ]$timeElapsedRational <- NA
              dat[i, ]$timeElapsedFEM <- NA
              dat[i, ]$timeElapsedTrue <- NA
            })
  slackr_msg(text = paste0("Current parameters are rho = ", rho, 
                          ", kappa = ", kappa,
                          ", m = ", m, 
                          ", alpha = ", alpha,
                          ", nu = ", nu,
                          " , iteration ", i, 
                          " out of ", nrow(dat)), 
             channel = "#research")
}
save(dat, file = here::here("data_files/error_comparison_results.RData"))
```



```{r}
load(here::here("data_files/error_comparison_results.RData"))

# reshape long first
dat_long <- dat %>%
  pivot_longer(
    cols = c(L2ErrorRational, LinfErrorRational,
             L2ErrorFEM, LinfErrorFEM),
    names_to = c("metric", "method"),
    names_pattern = "(L2Error|LinfError)(Rational|FEM)",
    values_to = "error"
  )

# dataset for Rational
datRat <- dat_long %>%
  filter(method == "Rational") %>%
  mutate(
    errorRat = error,
    rat = paste0(metric, "Rational")
  ) %>%
  select(alpha, m, rho, errorRat, rat)

# dataset for FEM
datFEM <- dat_long %>%
  filter(method == "FEM") %>%
  mutate(
    errorFEM = error,
    FEM = paste0(metric, "FEM")
  ) %>%
  select(alpha, m, rho, errorFEM, FEM)



datRat$rho = factor(datRat$rho, levels = c("0.01", "0.05", "0.1", "0.2"))
datRat$rat = factor(datRat$rat, levels = c("L2ErrorRational", "LinfErrorRational"))
levels(datRat$rho) = c("0.1" = "$\\rho = 0.1$", "0.5" = "$\\rho = 0.5$", "1" = "$\\rho = 1$", "2" = "$\\rho = 2$")
levels(datRat$rat) = c("L2ErrorRational" = "$L_2(\\Gamma\\times\\Gamma)$", "LinfErrorRational" = "$L_\\infty(\\Gamma\\times\\Gamma)$")


datFEM$rho = factor(datFEM$rho, levels = c("0.01", "0.05", "0.1", "0.2"))
datFEM$FEM = factor(datFEM$FEM, levels = c("L2ErrorFEM", "LinfErrorFEM"))
levels(datFEM$rho) = c("0.01" = "$\\rho = 0.1$", "0.05" = "$\\rho = 0.5$", "0.1" = "$\\rho = 1$", "0.2" = "$\\rho = 2$")
levels(datFEM$FEM) = c("L2ErrorFEM" = "$L_2(\\Gamma\\times\\Gamma)$", "LinfErrorFEM" = "$L_\\infty(\\Gamma\\times\\Gamma)$")




errorRatplot <- ggplot(datRat, aes(alpha, errorRat, colour = as.factor(m))) + 
  facet_grid(rat ~ rho) +
  geom_line(linewidth = 0.6) +
  scale_y_log10(n.breaks = 5) +
  scale_x_continuous(n.breaks = 6) +
  theme_bw() +
  theme(panel.spacing = unit(0.3, "cm"), 
        text = element_text(family = "Palatino"),
        plot.title = element_text(hjust = 0.5, size = 16),
        strip.text = element_text(size = 12),        # Panel titles
        axis.title = element_text(size = 14),        # Axis titles
        axis.text = element_text(size = 12),         # Axis text
        legend.title = element_text(size = 14),      # Legend title
        legend.text = element_text(size = 12)) +
  labs(x = "$\\alpha\\mbox{ }(\\mbox{Smoothness parameter})$", y = "$\\mbox{Covariance Error}$", color = "$m$")



errorFEMplot <- ggplot(datFEM, aes(alpha, errorFEM, colour = as.factor(m))) + 
  facet_grid(FEM ~ rho) +
  geom_line(linewidth = 0.6) +
  scale_y_log10(n.breaks = 5) +
  scale_x_continuous(n.breaks = 6) +
  theme_bw() +
  theme(panel.spacing = unit(0.3, "cm"), 
        text = element_text(family = "Palatino"),
        plot.title = element_text(hjust = 0.5, size = 16),
        strip.text = element_text(size = 12),        # Panel titles
        axis.title = element_text(size = 14),        # Axis titles
        axis.text = element_text(size = 12),         # Axis text
        legend.title = element_text(size = 14),      # Legend title
        legend.text = element_text(size = 12)) +
  labs(x = "$\\alpha\\mbox{ }(\\mbox{Smoothness parameter})$", y = "$\\mbox{Covariance Error}$", color = "$m$")
```


```{r, eval = TRUE, out.width="1200px", out.height="600px", fig.cap = captioner("Covariance error for the tadpole graph.")}
errorRatplot
```


```{r, eval = TRUE, out.width="1200px", out.height="600px", fig.cap = captioner("Covariance error for the tadpole graph.")}
errorFEMplot
```

```{r}
load(here::here("data_files/error_comparison_results.RData"))

dat_new <- dat %>%
  pivot_longer(
    cols = c(L2ErrorRational, LinfErrorRational,
             L2ErrorFEM, LinfErrorFEM),
    names_to = c("metric", "method"),
    names_pattern = "(L2Error|LinfError)(Rational|FEM)",
    values_to = "error"
  )

dat_new$rho = factor(dat_new$rho, levels = c("0.01", "0.05", "0.1", "0.2"))
dat_new$metric = factor(dat_new$metric, levels = c("L2Error", "LinfError"))
dat_new$method = factor(dat_new$method, levels = c("Rational", "FEM"))
levels(dat_new$rho) = c("0.01" = "$\\rho = 0.1$", "0.05" = "$\\rho = 0.5$", "0.1" = "$\\rho = 1$", "0.2" = "$\\rho = 2$")
levels(dat_new$metric) = c("L2Error" = "$L_2(\\Gamma\\times\\Gamma)$", "LinfError" = "$L_\\infty(\\Gamma\\times\\Gamma)$")
levels(dat_new$method) = c("Rational" = "RAT", "FEM" = "FEM")

errorRatplot <- ggplot(dat_new, aes(alpha, error, colour = as.factor(m), linetype = method)) + 
  facet_grid(metric ~ rho) +
  geom_line(linewidth = 0.6) +
  scale_y_log10(n.breaks = 5) +
  scale_x_continuous(n.breaks = 6) +
  scale_linetype_manual(values = c("solid", "dotdash")) + 
  #scale_color_manual(values = c("black", "red3", "blue3", "darkgreen", "orange")) +
  theme_bw() +
  theme(panel.spacing = unit(0.3, "cm"), 
        text = element_text(family = "Palatino"),
        plot.title = element_text(hjust = 0.5, size = 16),
        strip.text = element_text(size = 12),        # Panel titles
        axis.title = element_text(size = 14),        # Axis titles
        axis.text = element_text(size = 12),         # Axis text
        legend.title = element_text(size = 14),      # Legend title
        legend.text = element_text(size = 12)) +
  labs(x = "$\\alpha\\mbox{ }(\\mbox{Smoothness parameter})$", y = "$\\mbox{Covariance Error}$", color = "$m$", linetype = "Method")
```


```{r, eval = TRUE, out.width="1200px", out.height="600px", fig.cap = captioner("Covariance error for the tadpole graph.")}
errorRatplot
```



















