---
title: "Comparison between FEM-based and ratapprox-based covariance appriximation"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendeblack HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(2) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = FALSE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(MetricGraph)
library(Matrix)
library(ggplot2)
library(reshape2)
library(dplyr)
library(viridis)
library(plotly)
library(patchwork)
library(slackr)
source("keys.R")
slackr_setup(token = token) # token comes from keys.R
```

```{r}
reticulate::use_python(
  "/home/rierasl/miniconda3/envs/phdenv/bin/python",
  required = TRUE
)

reticulate::py_config()
```


```{r}
capture.output(
  knitr::purl(here::here("all_functions.Rmd"), output = here::here("all_functions.R")),
  file = here::here("old/purl_log.txt")
)
capture.output(
  knitr::purl(here::here("matern_functions.Rmd"), output = here::here("matern_functions.R")),
  file = here::here("old/purl_log.txt")
)

source(here::here("all_functions.R"))
source(here::here("matern_functions.R"))
```





```{r}
# parameters
h <- 0.05
kappa <- 10
sigma <- 0.8

m <- 4
n.overkill <- 1000

alpha_vector <- seq(0.75, 3, by = 0.25)



FLIPPED <- FALSE


# build a graph with a mesh
graph_initial <- gets.graph.tadpole(flip_edge = FLIPPED)
graph <- graph_initial$clone()


graph_initial$build_mesh(h = h)

mesh_XY <- graph_initial$mesh$V %>% as.data.frame()

mesh_locations <- graph_initial$get_mesh_locations() %>% 
  as.data.frame() %>% 
  mutate(dummy = 1) %>%
  rename(edge_number = V1, distance_on_edge = V2)

# add mesh locations as observations
graph$add_observations(
  data = mesh_locations,
  normalized = TRUE)

# add observations as vertices
graph$observation_to_vertex()

data <- graph$get_data()

order <- data %>%
  as.data.frame() %>%
  select(.coord_x, .coord_y) %>%
  rename(X = .coord_x, Y = .coord_y)


cov_true <- matrix(NA, nrow = nrow(mesh_XY), ncol = length(alpha_vector))
cov_rat <- matrix(NA, nrow = nrow(mesh_XY), ncol = length(alpha_vector))
cov_FEM <- matrix(NA, nrow = nrow(mesh_XY), ncol = length(alpha_vector))

var_true <- cov_true
var_rat <- cov_rat
var_FEM <- cov_FEM

error_fem_true <- rep(NA, length(alpha_vector))
error_rat_true <- rep(NA, length(alpha_vector))

for (i in seq_along(alpha_vector)) {
alpha <- alpha_vector[i]
nu <- alpha - 0.5
tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))

Approx_Sigma <- rat_covariance(
  graph = graph, 
  kappa = kappa, 
  tau = tau, 
  alpha = alpha, 
  m = m,
  type_rational_approx = "chebfun",
  type_interp = "spline",
  build_cov = TRUE)

digits <- 10

idx <- match(
  paste(round(mesh_XY$X, digits), round(mesh_XY$Y, digits)),
  paste(round(order$X, digits), round(order$Y, digits))
)


Approx_Sigma <- Approx_Sigma[idx, idx]


graph_initial$compute_fem()

True_Sigma <- gets_true_cov_mat(
  graph = graph_initial, 
  kappa = kappa, 
  tau = tau, 
  alpha = alpha, 
  n.overkill = n.overkill)


op <- matern.operators(alpha = alpha, 
                      kappa = kappa, 
                      tau = tau,
                      m = m, 
                      graph = graph_initial)

FEM_Sigma <- covariance_mesh(op)

cov_true[,i] <- True_Sigma[,2]
cov_rat[,i] <- Approx_Sigma[,2]
cov_FEM[,i] <- FEM_Sigma[,2]

var_true[,i] <- diag(True_Sigma)
var_rat[,i] <- diag(Approx_Sigma)
var_FEM[,i] <- diag(FEM_Sigma)


error_rat_true[i] <- sqrt(as.double(t(graph_initial$mesh$weights)%*%(True_Sigma - Approx_Sigma)^2%*%graph_initial$mesh$weights))
error_fem_true[i] <- sqrt(as.double(t(graph_initial$mesh$weights)%*%(True_Sigma - FEM_Sigma)^2%*%graph_initial$mesh$weights))

}

diff_true_rat <- abs(cov_true - cov_rat)
diff_true_FEM <- abs(cov_true - cov_FEM)

```





```{r}
RAT_FEM_DIFF <- graph.plotter.3d.comparer(graph_initial, diff_true_rat, diff_true_FEM, alpha_vector, legend_title =  "α", true_text = "$|\\varrho_{\\alpha}(v_2,\\cdot) - \\varrho(v_2,\\cdot)|$", approx_text = "$|\\varrho^{\\alpha}_{h,m}(v_2,\\cdot) - \\varrho(v_2,\\cdot)|$", log_z = TRUE)
save(RAT_FEM_DIFF, file = here::here("data_files/RAT_FEM_DIFF.RData"))
#save_plotly_figure_fixed(RAT_FEM_DIFF, dpi = 100, scale = 2, viewer_change = 1) 
```




:::: {style="display: grid; grid-template-columns: 1370px 1000px 1000px; grid-column-gap: 0px;"}



::: {}

```{r, eval =TRUE, fig.height = 7, out.width="100%", fig.cap = captioner("Still.")}
load(here::here("data_files/RAT_FEM_DIFF.RData"))
RAT_FEM_DIFF
```


:::

::: {}

:::



::::















## References

```{r, eval = TRUE, purl = FALSE}
grateful::cite_packages(output = "paragraph", out.dir = ".")
```
