myggsave <- function(plot, width = 9.22, height = 7.05) {
  
  dir_to_save <- here::here("data_files/tikzpic")
  obj_name <- deparse(substitute(plot))
  tex_name <- file.path(dir_to_save, paste0(obj_name, ".tex"))
  
  # Create directory if it doesn't exist
  if (!dir.exists(dir_to_save)) dir.create(dir_to_save, recursive = TRUE)
  
  # FORCE LaTeX FONT HERE, comment the following if smth breaks
  library(tikzDevice)
  options(
    tikzDocumentDeclaration = "\\documentclass[tikz,border=0pt]{standalone}",
    tikzLatexPackages = c(
      "\\usepackage{tikz}",
      "\\usetikzlibrary{calc}",
      "\\usepackage[T1]{fontenc}",
      "\\usepackage[sc]{mathpazo}"
    ))
  # Comment until here if it fails
  # Save TikZ plot
  tikzDevice::tikz(tex_name, standAlone = TRUE, width = width, height = height)
  print(plot)
  dev.off()
  
  # Compile to PDF
  system(paste0("pdflatex -output-directory=", dir_to_save, " ", tex_name))
  
  # Remove auxiliary files
  aux_ext <- c(".aux", ".log", ".tex")
  for (ext in aux_ext) {
    f <- file.path(dir_to_save, paste0(obj_name, ext))
    if (file.exists(f)) file.remove(f)
  }
  
  # Remove any temporary raster images generated by tikzDevice
  ras_files <- list.files(
    dir_to_save,
    pattern = paste0(obj_name, "_ras[0-9]+\\.png$"),
    full.names = TRUE
  )
  if (length(ras_files) > 0) file.remove(ras_files)
  
  message("PDF saved at: ", file.path(dir_to_save, paste0(obj_name, ".pdf")))
}

save_dual_for_presentation <- function(obj) {
  obj_name <- deparse(substitute(obj))
  filename <- paste0(obj_name, ".RData")
  
  path1 <- here::here("data_files", filename)
  path2 <- file.path("~", "Desktop", "leninPresentations", "data_files", filename)
  
  e <- new.env()
  assign(obj_name, obj, envir = e)
  
  save(list = obj_name, file = path1, envir = e)
  save(list = obj_name, file = path2, envir = e)
  
  cat("Saved file in:\n",
      " -", path1, "\n",
      " -", path2, "\n")
}

save_plotly_figure_fixed <- function(fig,
                                     dpi = 600,
                                     scale = 2,
                                     viewer_change = 1) {
  
  folder <- here::here("data_files/plotlypdf")
  
  if (!dir.exists(folder)) {
    dir.create(folder, recursive = TRUE)
  }
  
  fig_name <- deparse(substitute(fig))
  
  file_name_pdf <- file.path(folder, paste0(fig_name, ".pdf"))
  file_name_png <- file.path(folder, paste0(fig_name, ".png"))
  
  
  # ---- CAMERA (correct Plotly location) ----
  cam <- fig$x$layoutAttrs[[1]]$scene$camera
  
  if (!is.null(cam)) {
    
    eye <- cam$eye
    center <- cam$center
    
    if (is.null(eye)) eye <- list(x = 1, y = 1, z = 1)
    if (is.null(center)) center <- list(x = 0, y = 0, z = 0)
    
    # vector center -> eye
    vx <- eye$x - center$x
    vy <- eye$y - center$y
    vz <- eye$z - center$z
    
    # norm (distance from center)
    norm_v <- sqrt(vx^2 + vy^2 + vz^2)
    
    if (norm_v > 0) {
      
      fig$x$layoutAttrs[[1]]$scene$camera$eye <- list(
        x = center$x + vx * viewer_change,
        y = center$y + vy * viewer_change,
        z = center$z + vz * viewer_change
      )
    }
  }
  
  # Save PDF
  plotly::save_image(
    fig,
    file_name_pdf,
    width = NULL,
    height = NULL,
    scale = scale
  )
  
  # Convert PDF to PNG
  cmd <- paste(
    "convert -density", dpi,
    "-background white -trim +repage",
    "-bordercolor white -border 10",
    shQuote(file_name_pdf),
    shQuote(file_name_png)
  )
  
  system(cmd, ignore.stdout = TRUE, ignore.stderr = TRUE)
  
  # Copy to presentation folder
  pres_dir <- path.expand("~/Desktop/leninPresentations/data_files")
  if (!dir.exists(pres_dir)) dir.create(pres_dir, recursive = TRUE)
  
  pres_png <- file.path(pres_dir, basename(file_name_png))
  pres_pdf <- file.path(pres_dir, basename(file_name_pdf))
  
  file.copy(file_name_png, pres_png, overwrite = TRUE)
  file.copy(file_name_pdf, pres_pdf, overwrite = TRUE)
  
  cat(
    "Files saved:\n",
    "  PDF:", file_name_pdf, "\n",
    "  PNG:", file_name_png, "\n",
    "  PDF copied to:", pres_pdf, "\n",
    "  PNG copied to:", pres_png, "\n",
    "  viewer change:", viewer_change, "\n"
  )
}


combine_pngs_with_gap <- function(png_files, output_file, gap = 20) {
  
  pres_dir <- path.expand("~/Desktop/leninPresentations/data_files")
  
  if (!dir.exists(pres_dir)) {
    dir.create(pres_dir, recursive = TRUE)
  }
  
  # build sequence: img spacer img spacer img
  parts <- c()
  
  for (i in seq_along(png_files)) {
    parts <- c(parts, shQuote(png_files[i]))
    
    if (i < length(png_files)) {
      parts <- c(parts, sprintf("\\( -size %dx1 xc:white \\)", gap))
    }
  }
  
  cmd <- paste(
    "convert",
    paste(parts, collapse = " "),
    "+append",
    shQuote(output_file)
  )
  
  system(cmd, ignore.stdout = TRUE, ignore.stderr = TRUE)
  
  # copy to presentation folder
  copied_file <- file.path(pres_dir, basename(output_file))
  file.copy(output_file, copied_file, overwrite = TRUE)
  
  cat(
    "Image created at:\n  ", output_file,
    "\nCopied to:\n  ", copied_file, "\n"
  )
}
