---
title: "Loglikelihood 1"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendeblack HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(Matrix)
library(MetricGraph)
library(ggplot2)
library(reshape2)
library(dplyr)
library(viridis)
library(plotly)
library(patchwork)
library(slackr)
source("keys.R")
slackr_setup(token = token) # token comes from keys.R
```


```{r}
capture.output(
  knitr::purl(here::here("all_functions.Rmd"), output = here::here("all_functions.R")),
  file = here::here("old/purl_log.txt")
)
capture.output(
  knitr::purl(here::here("matern_functions.Rmd"), output = here::here("matern_functions.R")),
  file = here::here("old/purl_log.txt")
)

source(here::here("all_functions.R"))
source(here::here("matern_functions.R"))
```


```{r}
edge1 <- rbind(c(0,0),c(1,0))
edge2 <- rbind(c(0,0),c(0,1))
edge3 <- rbind(c(0,1),c(-1,1))
theta <- seq(from=pi,to=3*pi/2,length.out = 20)
edge4 <- cbind(sin(theta),1+ cos(theta))
edges = list(edge1, edge2, edge3, edge4)
graph <- metric_graph$new(edges = edges)
```


```{r}
graph$build_mesh(h = 0.01)
```


```{r}
sigma <- 1.3
range <- 0.15
nu <- 0.8 
rspde.order <- 2
op <- matern.operators(nu = nu, range = range, sigma = sigma, 
                       parameterization = "matern",
                       m = rspde.order, graph = graph)  
u <- simulate(op)

obs.per.edge <- 100
obs.loc <- NULL
for(i in 1:graph$nE) {
  obs.loc <- rbind(obs.loc,
                   cbind(rep(i,obs.per.edge), runif(obs.per.edge)))
}
n.obs <- obs.per.edge*graph$nE
A <- graph$fem_basis(obs.loc)
```

```{r}
sigma.e <- 0.1
Y <- as.vector(A %*% u + sigma.e * rnorm(n.obs))
df_data <- data.frame(y = Y, edge_number = obs.loc[,1],
                        distance_on_edge = obs.loc[,2])
graph$add_observations(data = df_data, normalized = TRUE)
```

```{r}
fit <- graph_lme(y ~ -1, graph=graph, BC = 0,
            model = list(type = "WhittleMatern", alpha = 1))

summary(fit)
fit$loglik
```


```{r}
sigma_e <- fit$coeff$measurement_error
alpha <- 1
nu <- alpha - 1/2
tau <- fit$coeff$random_effects[1]
kappa <- fit$coeff$random_effects[2]

m <- graph$nV
n <- length(Y)


graph$observation_to_vertex()

data <- graph$get_data()

Y <- data$y

Q <- MetricGraph:::Qalpha1(
      theta = c(tau, kappa),
      graph = graph,
      BC = 0,
      build = TRUE)


barA <- cbind(matrix(0, nrow = n, ncol = m),
              Matrix::Diagonal(n))

Qp <- Q + 1/sigma_e^2 * t(barA) %*% barA 
mu <- 1/sigma_e^2 * solve(Qp, t(barA) %*% Y)

L <- chol(Q)
Lp <- chol(Qp)

loglik <- sum(log(diag(L))) +
  n*log(sigma_e) -
  sum(log(diag(Lp))) -
  0.5/sigma_e^2 * t(Y) %*% Y +
  0.5 * t(mu) %*% Qp %*% mu

loglik
```









































