---
title: "loglik3"
output: html_document
---

```{r}
# Create a clipboard button on the rendeblack HTML page
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```


```{r}
capture.output(
  knitr::purl("~/Desktop/ratAPPROX/all_functions.Rmd", output = "~/Desktop/ratAPPROX/all_functions.R"),
  file = here::here("old/purl_log.txt")
)
capture.output(
  knitr::purl("~/Desktop/ratAPPROX/matern_functions.Rmd", output = "~/Desktop/ratAPPROX/matern_functions.R"),
  file = here::here("old/purl_log.txt")
)

source("~/Desktop/ratAPPROX/all_functions.R")
source("~/Desktop/ratAPPROX/matern_functions.R")
```



```{r}
devtools::load_all("~/Desktop/MetricGraph")
```


```{r, eval = TRUE}
library(Matrix)
library(dplyr)
library(rSPDE)
source("~/Desktop/ratAPPROX/lenin/minimal_functions.R")
```


```{r}
edge1 <- rbind(c(0,0),c(1,0))
edge2 <- rbind(c(0,0),c(0,1))
edge3 <- rbind(c(0,1),c(-1,1))
theta <- seq(from=pi,to=3*pi/2,length.out = 20)
edge4 <- cbind(sin(theta),1+ cos(theta))
edges = list(edge1, edge2, edge3, edge4)
graph <- metric_graph$new(edges = edges)


alpha <- 2
nu <- alpha - 1/2
sigma <- 1.3
range <- 0.15
kappa <- sqrt(8*nu)/range
tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))

sigma_e <- 0.5

rspde.order <- 2


BC <- 0
```


```{r}
n.obs.per.edge <- 3
PtE <- NULL
for(i in 1:graph$nE){
  #add locations sampled at random to each edge
  PtE <- rbind(PtE, cbind(rep(i, n.obs.per.edge), runif(n.obs.per.edge)))
}

u <- sample_spde(range = range, sigma = sigma, alpha = alpha,
                 graph = graph, PtE = PtE, BC = BC)

Y <- u + sigma_e*rnorm(n.obs.per.edge * graph$nE)

df_data <- data.frame(y = Y, edge_number = PtE[,1],
                        distance_on_edge = PtE[,2])

graph$add_observations(data = df_data, normalized = TRUE)
```




# Loglikelihood using `graph_lme`

```{r}

fit <- graph_lme(y ~ -1, graph=graph, BC = BC,
                 model = list(type = "WhittleMatern", alpha = 2))

fit$loglik

```


```{r}
data <- graph$get_data()

Y <- data$y

# Precompute once
precomp <- precompute_alpha2(
  graph     = graph,
  manual_y  = Y,
  data_name = NULL,
  X_cov     = matrix(0, nrow = length(Y), ncol = 0),
  repl      = unique(graph$.__enclos_env__$private$data[[".group"]])
)

sigma_e      = fit$coeff$measurement_error
tau          = fit$coeff$random_effects[["tau"]]
kappa        = fit$coeff$random_effects[["kappa"]]

# Evaluate at any (sigma_e, tau, kappa) cheaply
loglik_val <- eval_likelihood_alpha2(
  sigma_e = sigma_e,
  tau = tau,
  kappa = kappa,
  precomp = precomp,
  BC      = 0
)
loglik_val
```



```{r}
fit <- graph_lme_alpha2(y ~ -1, graph=graph, BC = 0)

fit$loglik
```


```{r}
GRAPH <- graph$clone()
```



```{r}
graph$observation_to_vertex()

data <- graph$get_data()

Y <- data$y
n <- length(Y)

m <- 4
Approx_Sigma <- rat_covariance(
  graph = graph, 
  kappa = kappa, 
  tau = tau, 
  alpha = alpha, 
  m = m, build_cov = FALSE)

AT_Ut <- Approx_Sigma$A

Q <- Approx_Sigma$Q
L <- chol(Q)

Qp <- Q + 1/sigma_e^2 * t(AT_Ut) %*% AT_Ut
Lp <- chol(Qp)

muhat <- 1/sigma_e^2 * solve(Qp, t(AT_Ut) %*% Y)

loglik <- sum(log(diag(L))) -
  n*log(sigma_e) -
  sum(log(diag(Lp))) -
  0.5/sigma_e^2 * t(Y) %*% Y +
  0.5 * t(muhat) %*% Qp %*% muhat -
      0.5 * n * log(2*pi)

loglik
```

```{r}

Q <- MetricGraph:::Qalpha2(theta = c(tau, kappa),
                                         graph = GRAPH,
                                         BC = 1000,
                                         build = TRUE)

TT <- precomp$Tc

Lv <- chol(TT %*% Q %*% t(TT))

SIGMA <- sqrt(gamma(nu) / (tau^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))



loglik <- 0

PtE <- GRAPH$get_PtE() # data location, edge_number, distance_on_edge (norm)

n <- nrow(PtE)
obs.edges <- precomp$obs.edges # edges where data is

aux_list1 <- list()
aux_list2 <- list()
De <- gets_De_from_U(GRAPH, alpha)
for (e in seq_along(obs.edges)){
  edge_name <- paste0("edge_", e)
  ell <- GRAPH$edge_lengths[e] # get edge_length of edge e
  tt <- PtE[PtE[,1] == e, 2]*ell # get the edge coordinate location
  Sigma_e <- gets_Sigma_e(t_vector = tt, 
                         kappa = kappa,
                         alpha = alpha,
                         sigma = SIGMA,
                         sigma_e = sigma_e,
                         ell = ell)
  chol_Sigma_e <- chol(Sigma_e)
  y_e <- precomp$y$repl_1[[edge_name]]
  
  Sigma_e_inv_y_e <- solve(Sigma_e, y_e)
  loglik <- loglik - # accumulates the sum
    sum(log(diag(chol_Sigma_e))) - # this is -0.5*log|Sigma_e|
    0.5 * t(y_e) %*% Sigma_e_inv_y_e # this is -0.5*y_e^\top Sigma_e^{-1}y_e
  
  list_mat_Se <- list()
  for (i in 1:length(tt)) {
    list_mat_Se[[i]] <- S_mat(t1 = tt[i],
                              kappa = kappa,
                              alpha = alpha,
                              sigma = SIGMA,
                              ell = ell)
  }
  Se <- do.call(rbind, list_mat_Se)
  SeDe <- Se %*% De[[e]]
  aux_list1[[e]] <- t(SeDe) %*% solve(Sigma_e, SeDe)
  aux_list2[[e]] <- t(SeDe) %*% Sigma_e_inv_y_e
}

Qv_tilde <- TT %*% (Q + Reduce(`+`, aux_list1)) %*% t(TT)
Lv_tilde <- chol(Qv_tilde)
mu <- solve(Qv_tilde, TT %*% Reduce(`+`, aux_list2))

loglik <- loglik +
  sum(log(diag(Lv))) - # this is 0.5*log|Qv|
  sum(log(diag(Lv_tilde))) + # this is -0.5*log|Qv_tilde|
  0.5 * t(mu) %*% Qv_tilde %*% mu -
  0.5 * n * log(2*pi)

loglik

```






```{r}

```
















