---
title: "loglik1"
output: html_document
---



```{r}
# Create a clipboard button on the rendeblack HTML page
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(Matrix)
library(dplyr)
library(rSPDE)
devtools::load_all("~/Desktop/MetricGraph")
```


```{r}
edge1 <- rbind(c(0,0),c(1,0))
edge2 <- rbind(c(0,0),c(0,1))
edge3 <- rbind(c(0,1),c(-1,1))
theta <- seq(from=pi,to=3*pi/2,length.out = 20)
edge4 <- cbind(sin(theta),1+ cos(theta))
edges = list(edge1, edge2, edge3, edge4)
graph <- metric_graph$new(edges = edges)
graph_clone <- graph$clone()
```


```{r}
graph$build_mesh(h = 0.01)
```


```{r}
alpha <- 1
nu <- alpha - 1/2
sigma <- 1.3
range <- 0.15
kappa <- sqrt(8*nu)/range
tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))  


rspde.order <- 2



op <- matern.operators(alpha = alpha, 
                       kappa = kappa,
                       tau = tau,
                       parameterization = "spde",
                       m = rspde.order, 
                       graph = graph)  
```


```{r}
u <- simulate(op)

obs.per.edge <- 100
obs.loc <- NULL
for(i in 1:graph$nE) {
  obs.loc <- rbind(obs.loc,
                   cbind(rep(i,obs.per.edge), runif(obs.per.edge)))
}
n.obs <- obs.per.edge*graph$nE
A <- graph$fem_basis(obs.loc)
```

```{r}
sigma_e <- 0.5
Y <- as.vector(A %*% u + sigma_e * rnorm(n.obs))
df_data <- data.frame(y = Y, edge_number = obs.loc[,1],
                        distance_on_edge = obs.loc[,2])
graph_clone$add_observations(data = df_data, normalized = TRUE)
```

```{r}
fit <- graph_lme(y ~ -1, graph=graph_clone, BC = 0,
            model = list(type = "WhittleMatern", alpha = 1))

summary(fit)
fit$loglik
```


```{r}
sigma_e <- fit$coeff$measurement_error
tau <- fit$coeff$random_effects[1]
kappa <- fit$coeff$random_effects[2]

m <- graph$nV
n <- length(Y)


graph_clone$observation_to_vertex()

data <- graph_clone$get_data()

Y <- data$y

Q <- MetricGraph:::Qalpha1(
      theta = c(tau, kappa),
      graph = graph_clone,
      BC = 0,
      build = TRUE)

L <- chol(Q)

barA <- cbind(matrix(0, nrow = n, ncol = m),
              Matrix::Diagonal(n))

Qp <- Q + 1/sigma_e^2 * t(barA) %*% barA 
mu <- 1/sigma_e^2 * solve(Qp, t(barA) %*% Y)


Lp <- chol(Qp)

loglik <- sum(log(diag(L))) -
  n*log(sigma_e) -
  sum(log(diag(Lp))) -
  0.5/sigma_e^2 * t(Y) %*% Y +
  0.5 * t(mu) %*% Qp %*% mu -
      0.5 * n * log(2*pi)

loglik
```




```{r}

```





































