---
title: "loglik3"
output: html_document
---

```{r}
# Create a clipboard button on the rendeblack HTML page
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = TRUE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r}
devtools::load_all("~/Desktop/MetricGraph")
```


```{r, eval = TRUE}
library(Matrix)
library(dplyr)
library(rSPDE)
source("~/Desktop/ratAPPROX/lenin/minimal_functions.R")
```


```{r}
edge1 <- rbind(c(0,0),c(1,0))
edge2 <- rbind(c(0,0),c(0,1))
edge3 <- rbind(c(0,1),c(-1,1))
theta <- seq(from=pi,to=3*pi/2,length.out = 20)
edge4 <- cbind(sin(theta),1+ cos(theta))
edges = list(edge1, edge2, edge3, edge4)
graph <- metric_graph$new(edges = edges)


alpha <- 2
nu <- alpha - 1/2
sigma <- 1.3
range <- 0.15
kappa <- sqrt(8*nu)/range
tau <- sqrt(gamma(nu) / (sigma^2 * kappa^(2*nu) * (4*pi)^(1/2) * gamma(nu + 1/2)))

sigma_e <- 0.5

rspde.order <- 2
```


```{r}
n.obs.per.edge <- 3
PtE <- NULL
for(i in 1:graph$nE){
  #add locations sampled at random to each edge
  PtE <- rbind(PtE, cbind(rep(i, n.obs.per.edge), runif(n.obs.per.edge)))
}

u <- sample_spde(range = range, sigma = sigma, alpha = alpha,
                 graph = graph, PtE = PtE)

Y <- u + sigma_e*rnorm(n.obs.per.edge * graph$nE)

df_data <- data.frame(y = Y, edge_number = PtE[,1],
                        distance_on_edge = PtE[,2])

graph$add_observations(data = df_data, normalized = TRUE)
```




# Loglikelihood using `graph_lme`

```{r}

BC <- 0
fit <- graph_lme(y ~ -1, graph=graph, BC = BC,
                 model = list(type = "WhittleMatern", alpha = 2))

fit$loglik

```


```{r}
data <- graph$get_data()

Y <- data$y

# Precompute once
precomp <- precompute_alpha2(
  graph     = graph,
  manual_y  = Y,
  data_name = NULL,
  X_cov     = matrix(0, nrow = length(Y), ncol = 0),
  repl      = unique(graph$.__enclos_env__$private$data[[".group"]])
)

# Evaluate at any (sigma_e, tau, kappa) cheaply
loglik_val <- eval_likelihood_alpha2(
  sigma_e      = fit$coeff$measurement_error,
  tau          = fit$coeff$random_effects[["tau"]],
  kappa        = fit$coeff$random_effects[["kappa"]],
  precomp = precomp,
  BC      = 0
)
loglik_val
```



```{r}
fit <- graph_lme_alpha2(y ~ -1, graph=graph, BC = 0)

fit$loglik
```



